export const CATEGORIES = [
    { key: 'accesorios', label: { es: 'Accesorios', en: 'Accessories' } },
    { key: 'chapa_pintura', label: { es: 'Chapa y pintura', en: 'Body & paint' } },
    { key: 'combustible', label: { es: 'Combustible', en: 'Fuel' } },
    { key: 'electricidad', label: { es: 'Electricidad', en: 'Electricity' } },
    { key: 'estacionamiento', label: { es: 'Estacionamiento', en: 'Parking' } },
    { key: 'extintor', label: { es: 'Extintor', en: 'Extinguisher' } },
    { key: 'grua_asistencia', label: { es: 'Grúa / asistencia', en: 'Towing' } },
    { key: 'lavado', label: { es: 'Lavado', en: 'Washing' } },
    { key: 'mantenimiento', label: { es: 'Mantenimiento', en: 'Maintenance' } },
    { key: 'mejoras_tuning', label: { es: 'Mejoras / tuning', en: 'Improvements' } },
    { key: 'multas', label: { es: 'Multas', en: 'Fines' } },
    { key: 'neumaticos', label: { es: 'Neumáticos', en: 'Tires' } },
    { key: 'patente', label: { es: 'Patente', en: 'Registration' } },
    { key: 'peajes', label: { es: 'Peajes', en: 'Tolls' } },
    { key: 'reparacion', label: { es: 'Reparación', en: 'Repairs' } },
    { key: 'reparaciones_mecanicas', label: { es: 'Reparaciones mecánicas', en: 'Mechanical repairs' } },
    { key: 'repuestos', label: { es: 'Repuestos', en: 'Parts' } },
    { key: 'seguro', label: { es: 'Seguro', en: 'Insurance' } },
    { key: 'service', label: { es: 'Service', en: 'Service' } },
    { key: 'vtv_itv', label: { es: 'VTV / ITV', en: 'Inspection' } },
    { key: 'otros', label: { es: 'Otros', en: 'Other' } },
]