export type ExpenseCategory =
    | 'combustible'
    | 'mantenimiento'
    | 'service'
    | 'reparacion'
    | 'repuestos'
    | 'neumaticos'
    | 'seguro'
    | 'patente'
    | 'vtv'
    | 'estacionamiento'
    | 'peajes'
    | 'lavado'
    | 'multas'
    | 'accesorios'